name: Release

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Cache Bun dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Install dependencies
              run: bun install

            - name: Type check
              run: bun run typecheck:tsgo

            - name: Lint
              run: bun run lint

            - name: Build userscript
              run: bun run build

            - name: Extract version
              id: version
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: |
                  VERSION=$(grep '@version' src/setup.ts | sed -E 's/.*@version[[:space:]]+([0-9.]+).*/\1/')
                  echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Create Release
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v${{ steps.version.outputs.version }}
                  name: Release v${{ steps.version.outputs.version }}
                  files: dist/tampermonkey_vim_mode.js
                  generate_release_notes: true
